---
services:
  - docker

install:
  - docker build -t sterexx/plex_symlinker-dev -f Dockerfile.dev .

script:
  - docker run -t sterexx/plex_symlinker-dev bundle exec standardrb
  - docker run -t sterexx/plex_symlinker-dev bundle exec rake
