---
services:
  - docker

install:
  - docker build -t "$DOCKER_HUB_REPOSITORY"-dev -f Dockerfile.dev .

script:
  - docker run -t "$DOCKER_HUB_REPOSITORY"-dev bundle exec standardrb
  - docker run -t "$DOCKER_HUB_REPOSITORY"-dev bundle exec rake

deploy:
  provider: script
  script: bin/docker-build
  on:
    branch: master
