FROM ruby:slim

RUN apt-get update && \
        apt-get install -y libtag1-dev libtag-extras-dev g++ make

WORKDIR /app

COPY ./lib/plex_symlinker/version.rb ./lib/plex_symlinker/version.rb
COPY ./Gemfile* ./
COPY ./plex_symlinker.gemspec ./

RUN bundle install

COPY ./ ./

CMD bundle exec rake
