#!/usr/bin/env bash

docker run -it --rm -v "$1":/app/source -v "$2":/app/target --env VIRTUAL_FILES_DIRECTORY="$1" symlinker

echo "Fixing permissions for newly created symlinks..."
sudo chown -R $(id -u):$(id -g) $2
