#!/usr/bin/env bash

echo "Creating target directory with current user permissions..."
mkdir -p $2

echo "Creating symlinks..."
docker run -it --user "$(id -u):$(id -g)" --rm -v "$1":/app/source -v "$2":/app/target --env VIRTUAL_FILES_DIRECTORY="$1" symlinker
