#!/usr/bin/env ruby

require "bundler/setup"
require "plex/symlinker"
require "slop"

opts = Slop.parse do |o|
  o.string "--virtual-files-directory", "Overrides the base source directory in the generated symlinks"
  o.on "--help" do
    puts o
    exit
  end
end

if opts.arguments.size != 2
  fail ArgumentError, "Please provide at least source and target directory."
end

files_dir, symlinks_dir = opts.arguments

Plex::Symlinker::Operation.new(files_dir, symlinks_dir, virtual_files_base_dir: opts[:virtual_files_directory]).perform

